window.sampleData = {
    "title":"Sample Hex Map",
    "style":{
        "stroke":"black",
        "stroke-width":0.5
    },
    "tiles":[
        {
            "tileTitle":"Bardivik",
            "background":"white",
            "shapes":[
                ["poly",[[0,0],[8,5],[0,10]],{"fill":"orange"}],
                ["poly",[[16,0],[8,5],[16,10]],{"fill":"orange"}],
                ["rect",0,11,16,3,{"fill":"black"}],
                ["poly",[[8,1],[6,3],[10,3]],{"fill":"black"}],
                ["rect",6,3,4,8,{"fill":"black"}],
                ["rect",7,4,2,3,{"fill":"white"}],
            ]
        },
        {
            "tileTitle":"Water",
            "background":"lightblue",
            "shapes":[]
        },
        {
            "tileTitle":"Swamp",
            "background":"aquamarine",
            "shapes":[]
        },
        {
            "tileTitle":"Farmland",
            "background":"lightgreen",
            "shapes":[]
        },
        {
            "tileTitle":"Forest",
            "background":"green",
            "shapes":[
                ["poly",[[5,3],[4,5],[6,5]],{"fill":"darkgreen"}],
                ["poly",[[5,4],[4,6],[6,6]],{"fill":"darkgreen"}],
                ["poly",[[5,5],[4,7],[6,7]],{"fill":"darkgreen"}],
            ]
        },
        {
            "tileTitle":"Hills",
            "background":"tan",
            "shapes":[]
        },
        {
            "tileTitle":"Hlegmoor",
            "background":"white",
            "shapes":[
                ["rect",0,10,16,4,{"fill":"black"}],
                ["rect",2,6,6,5,{"fill":"black"}],
                ["rect",6.5,4,1,3,{"fill":"black"}],
                ["poly",[[1.5,6],[8.5,6],[5,4.5]],{"fill":"black"}],
                ["rect",2,6,6,5,{"fill":"black"}],
                ["rect",3,6.5,1,1,{"fill":"white"}],
                ["rect",5,7,1.5,3,{"fill":"white"}],
                ["rect",10,7,4,3,{"fill":"black"}],
                ["poly",[[9.5,7],[11.5,5.5],[14.5,7]],{"fill":"black"}],
                ["rect",11,8,1,2,{"fill":"white"}],
            ]
        },
    ],
    "map":[
        "bbbcfffffff",
        "bbccfefffee",
        "bbcdeeeeeee",
        "badeeeeeeee",
        "bcdeeeeeeee",
        "bcdeeeedeee",
        "bcdeededeee",
        "bbccfddddde",
        "bbccffdbgdd",
        "bbccffddddd"
    ]
};
